FROM node:16-alpine AS builder
ENV NODE_ENV production
RUN apk add git
# Add a work directory
WORKDIR /app

VOLUME ./nodebuild/ ./build/

# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --production
# Copy app files
COPY . .
# Build the app
RUN yarn build

